<?php
namespace app\index\controller;
use think\Cache;
use think\Db;
use think\Controller;
use app\index\model\Category as cateModel;
use app\index\model\Item as itemModel;
use app\index\model\Group as groupModel;
use app\index\model\Article as articleModel;
use app\index\model\Image as imageModel;
class Index extends Base{

    //构造函数
    function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /*  首页
     *  【加盟行业、加盟项目排行、品牌精选模块（字、图）、项目推荐、行业资讯、品牌聚焦】
     * **/
    public function index(){

        //实例化模型
        $cateModel = new cateModel();
        $itemModel = new itemModel();
        $groupModel = new groupModel();
        $articleModel = new articleModel();
        $imageModel = new imageModel();
        //首页-行业分类
        $cateWhere['status'] = 1;
        $cateWhere['pid'] = 0;
        $cateList = $cateModel -> getCateDataList(['status'=>1,'pid'=>0],'reco desc','16',1);
        //首页加盟项目排行
        $hotItem = $itemModel -> getItemDataList(['status'=>1],'read_num desc','13',1);
        //首页-品牌精选【品牌推荐-图片推荐】-start
        $bwhere['gid'] = config('CHOICE');
        $imgIdStr = $groupModel -> getItemIdStr(['status'=>1,'reco_img'=>1],'addtime desc',5);//封面图
        $bwhere['reco_brand'] = 1;
        $brandIdStr = $groupModel -> getItemIdStr(['status'=>1,'reco_brand'=>1],'addtime desc',7);//品牌
        //查询出内容
        $itemWhere['id'] = array('in',$brandIdStr);
        $itemWhere['status'] = 1;
        $groupData['brand'] = $itemModel -> getItemDataList($itemWhere,'id desc','',1);
        $itemWhere['id'] = array('in',$imgIdStr);
        $groupData['image'] = $itemModel -> getItemDataList($itemWhere,'id desc','',2);
        //首页-品牌精选-end
        //推荐项目
        $recoItem = $itemModel -> getItemDataList(['status'=>1,'reco'=>1],'addtime desc',10,3);
        //首页行业资讯-start
        $imgData = $articleModel -> getArticleData(['status'=>1,'reco'=>1],'addtime desc',2,1);
        if($imgData) {
            foreach ($imgData as $key => $value) {
                $recoArticle[$key]['rArticle'] = $imgData[$key];
                //获取最新的文章 定义读取条数
                $num = $key * 7;
                $limit = $num . ',7';
                $recoArticle[$key]['article'] = $articleModel->getArticleData(['status'=>1,'reco'=>0], 'addtime desc', $limit, 2);
            }
        }else{
            $recoArticle = [];
        }
        //首页-行业资讯-end
        //品牌精选
        $brandList = $this -> getBrandList();
        //广告
        $imageData = $imageModel -> getImageDatList(['status'=>1,'web_page'=>1]);

        //分配变量渲染到页面
        $this -> assign('cateList',$cateList);//行业分类
        $this -> assign('hotItem',$hotItem);//加盟项目排行
        $this -> assign('groupData',$groupData);//品牌加盟精选
        $this -> assign('recoItem',$recoItem);//推荐项目
        $this -> assign('recoArticle',$recoArticle);//行业资讯
        $this -> assign('brandList',$brandList);//品牌聚焦
        $this -> assign('imageData',$imageData);//广告数据
        return view();
    }

    /*  首页  品牌聚焦    */
    public function getBrandList(){
        $dbBrand = db('brand');
        $brandwhere['status'] = 1 ;
        $brandData = $dbBrand -> where($brandwhere) -> order('addtime desc') -> select();
        //格式化数据
        foreach ($brandData as $key => $value) {
            $dataList[$key]['name'] = $value['name'];
            $dataList[$key]['img'] = empty($value['img']) ? '' : trim($value['img'],'.') ;
            $dataList[$key]['type'] = $value['type'];
            switch ($value['type']) {
                case 1://外链
                    $dataList[$key]['link'] = empty($value['link']) ? 'javascript:;' : $value['link'];
                    break;
                case 2://链接到项目
                    $dataList[$key]['link'] = empty($value['link']) ? '' : "../item/detail?id={$value['link']}";
                    break;
                case 3://链接到文章
                    $dataList[$key]['link'] = empty($value['link']) ? '' : "../article/detail?id={$value['link']}";
                    break;
                default://外链
                    $dataList[$key]['link'] = $value['link'];
                    break;
            }
        }
        return $dataList;
    }

    /*  排行榜 todo */
    public function rankinglist(){
        $itemModel = new itemModel();
        $cateModel = new cateModel();
        $articleModel = new articleModel();
        $imageModel = new imageModel();
        //推荐品牌排行榜
        $where['reco_brand'] = 1;
        $where['status'] = 1;
        $recoRank = $itemModel -> getItemDataList($where,'order desc,addtime desc',10,1);//where order limit type user debug
        //综合品牌排行榜  //精选推荐
        $synRank = $itemModel -> getItemDataList(['status'=>1],'read_num desc',10,1);//where order limit type user debug
        //十大品牌排行榜
        $cateData = $cateModel -> getBrandRanking(['pid'=>0],'order desc,id desc');
        foreach ($cateData as $key => $value) {
            $brandRank[$key]['cate_id'] = $value['id'];
            $brandRank[$key]['cate_name'] = $value['name'];
            $itemwhere['cate_id'] = array('in',$value['ids']);
            $itemwhere['status'] = 1;
            $brandRank[$key]['item_data'] = $itemModel -> getItemDataList($itemwhere,'read_num desc , id desc',10,1);
        }
        //项目推荐
        $recoItem = $itemModel -> getItemDataList(['status'=>1,'reco'=>1],'addtime desc',12,3);
        //行业资讯
        $artData['rArticle'] = $articleModel -> getArticleDataForReco(['status'=>1,'reco'=>1]);
        $artwhere['status'] = 1;
        $artwhere['id'] = ['neq',$artData['rArticle']['id']];
        $artData['aticle'] = $articleModel -> getArticleData($artwhere,'addtime desc',7,2);
        //广告
        $imageData = $imageModel -> getImageDatList(['status'=>1,'web_page'=>5]);
        //分配变量
        $this -> assign('recoRank',$recoRank);//推荐品牌排行榜
        $this -> assign('synRank',$synRank);//综合品牌排行榜  //精选推荐
        $this -> assign('brandRank',$brandRank);//十大品牌排行榜
        $this -> assign('recoItem',$recoItem);//项目推荐
        $this -> assign('artData',$artData);//行业分类
        $this -> assign('imageData',$imageData);//广告
//        echo "【推荐品牌排行榜】";dump($recoRank);
//        echo "【综合品牌排行榜  //精选推荐】";dump($synRank);
//        echo "【十大品牌排行榜】";dump($brandRank);die;
//        echo "【项目推荐】";dump($recoItem);
//        echo "【行业资讯】";dump($artData);die;
//        echo "【广告】";dump($imageData);die;
        return view();
    }

}
