<?php
namespace app\index\controller;
use think\Cache;
use think\Db;
use think\Controller;
use app\index\model\User as userModel;
use app\common\model\User as uModel;
use app\index\model\Consult as consultModel;
use app\index\model\Notice as noticeModel;
use app\index\model\Follow as followModel;
use app\index\model\Item as itemModel;
use app\index\model\Article as articleModel;
use app\index\model\Track as trackModel;

class user extends Base{

    private $userModel;
    private $uid;

    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 实例化y用户模型
         $this->userModel = model('user');

        $userModel = new uModel();
        $this -> uid = empty($_SESSION['jmzn_web']['uid']) ? false : $_SESSION['jmzn_web']['uid'];
        if(empty($this -> uid)){
            echo "请先登录";
            $this -> redirect('index/login/login');
        }else{
            $user = $userModel -> getUserData(['uid'=>$this -> uid],1);
            //分配变量
            $this -> assign('user',$user);
        }
    }

    /*  个人中心    */
    public function index(){
        $userModel = new uModel();
        $uid = empty($_SESSION['jmzn_web']['uid']) ? 25 : $_SESSION['jmzn_web']['uid'];
        //验证登录
        if(empty($uid)){
            echo "没登陆呢兄弟";
            $this -> redirect('index/login/login');
        }else{//获取用户信息
            //获取用户信息
            $user = $userModel -> getUserData(['uid'=>$uid],1);
            //分配变量
            $this -> assign('user',$user);
            return view();
        }
    }

    /*  我的消息    */
    public function message(){
        $consultModel = new consultModel();
        $noticeModel = new noticeModel();
//        获取推送消息
        $where['to_uid'] = $this -> uid;
        $where['type'] = 2;
        $where['status'] = 1;
        $page = '';
        $consult = $consultModel ->  getConsultListByPage($where,'addtime desc',10,3,$page );
        //评论和赞
        $getNoticeWhere['uid'] = $this -> uid;
        $getNoticeWhere['status'] = 1;
        $getNoticeWhere['type'] = array('in','1,2');
        $npage = '';
        $notice  = $noticeModel -> getNoticeDataByPage($getNoticeWhere , 'addtime  desc' , 10 , 1,$npage  );
//        分配变量
        $this -> assign('consult',$consult);//推送数据
        $this -> assign('notice',$notice);//评论和赞
        $this -> assign('page',$page);//推送分页数据
        $this -> assign('npage',$npage);//消息通知分页

        return view();
    }

    /*  我的关注    */
    public function focus(){
        //定义 && 接收 参数
        $followModel = new followModel();
        $itemModel = new itemModel;
        //获取关注项目的id
        $tids = $followModel -> getTid(['uid'=>$this -> uid,'ftype'=>1,'status'=>1]);
        $where['id'] = array('in',$tids);
        $page = '';//预定义 分页
        $data = $itemModel -> getItemDataListPage($where,false ,10,4,$page);
        //分配变量
        $this -> assign('data',$data);
        $this -> assign('page',$page);
        return view();
    }

    /*  我的收藏    */
    public function collect(){
        //定义参数 && 接收参数
        $followModel = new followModel();
        $itemModel = new itemModel;
        $articleModel = new articleModel();
        $type = $this -> request -> param('type');
        $type = empty($type) ? 0 : $type ;
        $ip = '';//预定义 项目分页
        $ap = '';//预定义 文章分页
        //收藏的项目
        $tids = $followModel -> getTid(['uid'=>$this -> uid,'ftype'=>2,'status'=>1]);
        $item = $itemModel -> getItemDataListPage(['id'=>['in',$tids]],false ,2,4,$ip);

        //收藏的文章
        $aIds = $followModel -> getTid(['uid'=>$this -> uid ,'status'=>1,'ftype'=>3]);
        $where['id'] = array('in',$aIds);
        $article = $articleModel -> getArticleDataByPage(['id'=>['in',$aIds],'type'=>$type],'addtime desc',1,3,$ap);//where/order/limit/type/user
        //分配变量
        $this -> assign('item',$item);
        $this -> assign('article',$article);
        $this -> assign('ap',$ap);
        $this -> assign('ip',$ip);
        return view();
    }
 /*  我的收藏-文章收藏    */
    public function articlecollect(){
        //定义参数 && 接收参数
        $followModel = new followModel();
        $articleModel = new articleModel();
        $type = $this -> request -> param('type');
        $type = empty($type) ? 0 : $type ;
        $page = '';//预定义 文章分页

        //收藏的文章
        $aIds = $followModel -> getTid(['uid'=>$this -> uid ,'status'=>1,'ftype'=>3]);
        $where['id'] = array('in',$aIds);
        $article = $articleModel -> getArticleDataByPage(['id'=>['in',$aIds],'type'=>$type],'addtime desc',1,3,$page);
        //分配变量
        $this -> assign('article',$article);//文章数据
        $this -> assign('page',$page);//分页
        $this -> assign('type',$type);//资讯类型
        return view();
    }
    public function leavemessage(){
        //接收 && 定义变量
        $consultModel = new consultModel();
        $page = '';
        $data = $consultModel -> getMyConsultByPage(['to_uid'=>$this->uid,'type'=>1,'status'=>1,'item_id'=>['neq',0]],'id desc',1,$page);
        //分配变量
        $this -> assign('data',$data);
        $this -> assign('page',$page);
        return view();
    }

    /*  我的足迹    */
    public function footmark(){
        //接收 && 定义 参数
        $itemModel = new itemModel();
        $trackModel = new trackModel();
        $page = '';
        //项目id
        $itemIdStr = $trackModel -> getMyTrackTid(['uid'=>$this->uid,'status'=>1]);
        $data = $itemModel -> getItemDataListPage(['id'=>['in',$itemIdStr],'status'=>1],false,7,4,$page);

        //分配变量
        $this -> assign('data',$data);
        $this -> assign('page',$page);
        return view();
    }

    /*  企业中心    */
    public function account(){
        $info = input('post.');
        if(empty($info)){
            $userModel = new uModel();
            $data = $userModel -> getUserData(['uid'=>$this -> uid],1);
//            dump($data);die;
            $this -> assign('data',$data);
            return view();
        }else{
            if(!empty($info['logo'])){          //logo cname address email bname
                $data['logo'] = $info['logo'];
            }
            if(!empty($info['cname'])){
                $data['cname'] = $info['cname'];
            }
            if(!empty($info['address'])){
                $data['address'] = $info['address'];
            }
            if(!empty($info['email'])){
                $data['email'] = $info['email'];
            }
            if(!empty($info['bname'])){
                $data['bname'] = $info['bname'];
            }
            $result = db('user') -> where(['uid'=>$this -> uid]) -> update($data);
            if(empty($result)){
                return ['code'=>400,'msg'=>'修改失败'];
            }else{
                return ['code'=>200,'msg'=>'修改成功'];
            }
        }
    }

    /*  投资者管理   */
    public function consult(){
        //接收 && 定义参数
        $consultModel = new consultModel();
        $type = $this -> request -> param('type');
        $read = $this -> request -> param('read');
        $page = '';
        //获取留言信息
        $where['type'] = (int)$type;
        $where['to_uid'] = $_SESSION['jmzn_web']['uid'];
        $where['read'] = (int)$read;
        $where['status'] = 1;
//        0未跟进/未回复1已跟进/已回复 2已签约/已查看 3放弃跟进/已催促  4 无效
        $data = $consultModel -> getConsultListByPage($where,'id desc',10,2,$page);
        //分配变量
        $this -> assign('data',$data);
        $this -> assign('page',$page);
        $this -> assign('read',(int)$read);
        $this -> assign('type',(int)$type);
        return view();
    }

    /*  意见反馈    */
    public function feedback(){
        return view();
    }

    /*  资料设置页面  */
    public function modify(){
        //获取用信息
        $info = input('post.');
        if(!empty($info)){
            if(!empty($info['avatar'])){
                $data['avatar'] = $info['avatar'];
            }
            if(!empty($info['name'])){
                $data['name'] = $info['name'];
            }
            if(!empty($info['username'])){
                $data['uname'] = base64_encode($info['username']);
            }
            if(!empty($info['sex'])){
                $data['sex'] = $info['sex'];
            }

            $result = db('user') -> where(['uid'=>$this -> uid]) -> update($data);
            if(empty($result)){
                return ['code'=>400,'msg'=>'修改失败'];
            }else{
                return ['code'=>200,'msg'=>'修改成功'];
            }
        }else{
            $userModel = new userModel();
            $where['uid'] = $this -> uid;
            $where['status'] = 1;
            $data = $userModel -> getUserDetail(['uid'=>$this -> uid,'status'=>1]);
            //分配变量
            $this -> assign('data',$data);
//            dump($data);die;
            $this -> assign('title','资料设置');
            return view();
        }
    }
    
    /*  todo   消息统计             count
     *  todo   个人信息接口         userCenter
     *  todo    修改个人信息接口    edit_user_data
     * **/

    //统计接口[消息][我的关注][我的收藏][我的留言]
    public function count(){
        if(empty($this -> user)){//验证登录
            $rinfo = $this -> returnCode['ERROR'][5];
            wapReturn($rinfo);
        }
        $data['no'] = db('notice') -> where(['uid'=>$this -> user['uid']]) -> count();
        $data['fo'] = db('follow') -> where(['ftype'=>1,'uid'=>$this -> user['uid'],'status'=>1]) -> count();
        $data['co'] = db('follow') -> where(['ftype'=>2,'uid'=>$this -> user['uid'],'status'=>1]) -> count();
        $data['lm'] = db('consult') -> where(['type'=>1,'uid'=>$this -> user['uid'],'status'=>['neq',4]]) -> count();
        //足迹内容3条
        $logWhere['uid'] = $this -> user['uid'];
        $logWhere['status'] = 1;
        //获取访问过的项目id
        $trackModel = model('track');
        $idStr = $trackModel -> getMyTrackTid($logWhere);
        $where['id'] = array('in',$idStr);
        $data['track'] = model('item') -> getItemDataList( $where , 'addtime desc' , 3 , 4 , $this -> user , $this -> debug );//where/order/limit/type/user/debug
        //评论内容3条
        $comwhere['form_uid'] = $this -> user['uid'];
        $comwhere['status'] = 1;
        $comwhere['to_type'] = 0;
        //分页
        $data['comment'] = model('comment') -> getCommentData($comwhere,'addtime desc',3,1,$this->user,$this -> debug);

        $rinfo = $this -> returnCode['SUCCESS'][0];
        $rinfo['data'] = $data;
        wapReturn($rinfo);

    }
    /*个人信息接口*/
    public function user_center(){
        //接收参数
        $user = $this -> user;
        if(empty($user)){
            $rinfo = $this -> returnCode['ERROR'][5];
            wapReturn($rinfo);
        }
        $uid = $this -> user['uid'];
        //获取用户信息
        $where['uid'] = $uid;
        $where['status'] = 1;
        $userData = $this -> userModel -> getUserDetail($where);
        if(empty($userData)){
            $rinfo = $this -> returnCode['ERROR'][4];
        }else{
            $rinfo = $this -> returnCode['SUCCESS'][0];
        }
        $rinfo['data'] = $userData;
        return json_encode($rinfo);
    }

    /*  修改个人信息接口    */
    public function change_user_data(){
        //验证登录
        if(empty($this -> user)){
            $rinfo = $this -> returnCode['ERROR'][5];
            wapReturn($rinfo);
        }
        //头像 昵称 性别
        $avatar = empty($_REQUEST['avatar']) ? false : $_REQUEST['avatar'];
        if(!empty($avatar)){
            $save['avatar'] = $avatar;
        }
        $name = empty($_REQUEST['name']) ? false : $_REQUEST['name'];
        if(!empty($name)) {
            $save['name'] = $name;
        }
        $username = empty($_REQUEST['username']) ? false : $_REQUEST['username'];
        if(!empty($username)){
            $save['uname'] = base64_encode($username);
        }
        $save['sex'] = empty($_REQUEST['sex']) ? 0 : 1 ;
        //查询用户信息是否存在
        $save['uid'] = $this -> user['uid'];
        $res = db('user') -> where($save) -> count();
        if($this -> debug == 1){
            echo db('user') -> getLastSql();
        }
        if(!empty($res)) {
            $rinfo = $this->returnCode['ERROR'][0];
            $rinfo['msg'] = '未发生任何变化';
            wapReturn($rinfo);
        }
        //修改用户信息
        $where['uid'] = $this -> user['uid'];
        unset($save['uid']);
        $res = $this -> userModel -> editUserData($where,$save);
        if(empty($res)){
            $rinfo = $this -> returnCode['ERROR'][0];
        }else{
            $rinfo = $this -> returnCode['SUCCESS'][0];
        }
        wapReturn($rinfo);
    }

    /*  修改企业信息  */
    public function change_ent_data(){
        //验证登录
        if(empty($this -> user)){
            $rinfo = $this -> returnCode['ERROR'][5];
            wapReturn($rinfo);
        }
        $type = db('user') -> where(['uid'=>$this -> user['uid']]) -> value('type');
        if($type != 1){//非企业用户
            $rinfo = $this -> returnCode['ERROR'][0];
            $rinfo['msg'] = '没有权限';
            wapReturn($rinfo);
        }
        //log
        $logo = empty($_REQUEST['logo']) ? false : $_REQUEST['logo'];
        if(!empty($logo)){
            $save['logo'] = $logo;
        }
        // cname
        $cname = empty($_REQUEST['cname']) ? false : $_REQUEST['cname'];
        if(!empty($cname)){
            $save['cname'] = $cname;
        }
        //bname
        $bname = empty($_REQUEST['bname']) ? false : $_REQUEST['bname'];
        if(!empty($bname)){
            $save['bname'] = $bname;
        }
        //address
        $address = empty($_REQUEST['address']) ? false : $_REQUEST['address'];
        if(!empty($address)){
            $save['address'] = $address;
        }
        //email
        $email = empty($_REQUEST['email']) ? false : $_REQUEST['email'];
        if(!empty($email)){
            $save['email'] = $cname;
        }
        //查询资料是否发生变化
        $save['uid'] = $this -> user['uid'];
        $res = db('user') -> where($save) -> count();
        if(!empty($res)){
            $rinfo = $this -> returnCode['ERROR'][0];
            $rinfo['msg'] = '未发生任何变化';
            wapReturn($rinfo);
        }
        //修改用户资料
        $where['uid'] = $this -> user['uid'];
        unset($save['uid']);
        $res = $this -> userModel -> editUserData($where,$save);
        if(empty($res)){
            $rinfo = $this -> returnCode['ERROR'][0];
        }else{
            $rinfo = $this -> returnCode['SUCCESS'][0];
        }
        wapReturn($rinfo);
    }
}